/* Token governance; agreement balance is intentionally separate from filtered consumption. */
(() => {
  'use strict';
  const OOP=(window.AVEVA_OOP=window.AVEVA_OOP||{});
  OOP.GovernanceService=class GovernanceService{
    constructor({repository,filterService,config}){Object.assign(this,{repository,filterService,config});}
    getAgreementLedger(){return this.repository.transactions.filter(row=>row.agreementId===this.config.activeAgreement);}
    getFilteredLedger(){return this.filterService.filterTransactionsByOrganization(this.getAgreementLedger(),this.filterService.values);}
    getFilteredConsumption(scope=this.filterService.dateScope()){return this.getFilteredLedger().filter(row=>this.filterService.inScope(row.date,scope)&&row.token<0);}
    empty(){return{total:null,balance:null,cur:'N/A',currentMonthLatestDate:null,prev:'N/A',cv:null,pv:null,mom:null,burn:null,days:null,forecast:null,contractEndDate:null,actualBalanceSeries:[],forecastSource:'Unavailable',risk:'N/A',top:['N/A',0],high:0,monthly:new Map(),monthlyTrend:new Map(),serviceConsumption:new Map(),filteredCount:0,periodTokenUsed:0,periodTokenRowCount:0,periodTokenNet:0};}
    calculate(){
      const scope=this.filterService.dateScope(),filters=this.filterService.values,ledgerAll=this.getAgreementLedger(),filteredAll=this.filterService.filterTransactionsByOrganization(ledgerAll,filters),burndownAll=[...(this.repository.burndown||[])].sort((a,b)=>a.date-b.date||b.sourceOrder-a.sourceOrder),sourceTx=filteredAll.filter(row=>this.filterService.inScope(row.date,scope)),consumption=sourceTx.filter(row=>row.token<0),periodTokenUsed=consumption.reduce((sum,row)=>sum+Math.abs(row.token),0),periodTokenRowCount=sourceTx.filter(row=>row.token!==null&&Number.isFinite(row.token)).length,periodTokenNet=sourceTx.reduce((sum,row)=>sum+row.token,0),dates=[...ledgerAll.map(row=>row.date),...burndownAll.map(row=>row.date)].filter(date=>date instanceof Date&&!Number.isNaN(date.getTime()));
      if(!dates.length)return this.empty();
      const cutoff=scope.mode==='ALL'?new Date(Math.max(...dates.map(date=>date.getTime()))):scope.end,ledgerToCutoff=ledgerAll.filter(row=>row.date<=cutoff),snapshots=ledgerToCutoff.filter(row=>row.balanceUniversal!==null),latestTime=snapshots.length?Math.max(...snapshots.map(row=>row.date.getTime())):null,sameTime=latestTime===null?[]:snapshots.filter(row=>row.date.getTime()===latestTime).sort((a,b)=>a.sourceOrder-b.sourceOrder),transactionSnapshot=sameTime[0]||null,burndownToCutoff=burndownAll.filter(row=>row.date<=cutoff),burndownSnapshot=burndownToCutoff[burndownToCutoff.length-1]||null,snapshotDate=burndownSnapshot?.date||transactionSnapshot?.date||null,transactionsAfterSnapshot=snapshotDate?ledgerAll.filter(row=>row.date>snapshotDate&&row.date<=cutoff):[],balance=burndownSnapshot?burndownSnapshot.balance+transactionsAfterSnapshot.reduce((sum,row)=>sum+row.token,0):transactionSnapshot?.balanceUniversal??null,total=periodTokenRowCount*this.config.tokenPerTransaction;
      const allMonthly=new Map();filteredAll.filter(row=>row.token<0).forEach(row=>{const period=`${row.date.getFullYear()}-${String(row.date.getMonth()+1).padStart(2,'0')}`;allMonthly.set(period,(allMonthly.get(period)||0)+Math.abs(row.token));});
      let currentPeriod;if(filters.year&&filters.month)currentPeriod=`${filters.year}-${String(filters.month).padStart(2,'0')}`;else{const candidates=filters.year?filteredAll.filter(row=>row.date.getFullYear()===Number(filters.year)):filteredAll;if(candidates.length){const latest=new Date(Math.max(...candidates.map(row=>row.date.getTime())));currentPeriod=`${latest.getFullYear()}-${String(latest.getMonth()+1).padStart(2,'0')}`;}else currentPeriod='N/A';}
      const currentMonthLatestDate=filteredAll.reduce((latest,row)=>{const period=`${row.date.getFullYear()}-${String(row.date.getMonth()+1).padStart(2,'0')}`;return period===currentPeriod&&(!latest||row.date>latest)?row.date:latest;},null);
      const previousPeriod=currentPeriod==='N/A'?'N/A':this.filterService.previousPeriod(currentPeriod),currentValue=allMonthly.has(currentPeriod)?allMonthly.get(currentPeriod):null,previousValue=allMonthly.has(previousPeriod)?allMonthly.get(previousPeriod):null,monthOverMonth=previousValue&&currentValue!==null?((currentValue-previousValue)/previousValue)*100:null;
      const latest=transactionsAfterSnapshot.length?new Date(Math.max(...transactionsAfterSnapshot.map(row=>row.date.getTime()))):snapshotDate,start=latest?new Date(latest):null;if(start){start.setDate(start.getDate()-29);start.setHours(0,0,0,0);}const burnSource=burndownToCutoff.length?[...burndownToCutoff,...transactionsAfterSnapshot]:ledgerAll,last30=latest?burnSource.filter(row=>row.token<0&&row.date>=start&&row.date<=latest).reduce((sum,row)=>sum+Math.abs(row.token),0):0,burnRate=last30>0?last30/30:null,daysRemaining=balance!==null&&balance>=0&&burnRate>0?balance/burnRate:null,forecast=daysRemaining!==null&&latest?new Date(latest.getTime()+daysRemaining*864e5):null;
      const dailyBalances=new Map();burndownToCutoff.forEach(row=>{const key=`${row.date.getFullYear()}-${String(row.date.getMonth()+1).padStart(2,'0')}-${String(row.date.getDate()).padStart(2,'0')}`;dailyBalances.set(key,{date:row.date,balance:row.balance});});const actualBalanceSeries=[...dailyBalances.values()].sort((a,b)=>a.date-b.date),contractEndYear=latest?latest.getFullYear()+(latest.getMonth()>=3?1:0):null,contractEndDate=contractEndYear===null?null:new Date(contractEndYear,2,31,23,59,59,999),octoberStart=contractEndYear===null?null:new Date(contractEndYear-1,9,1),nextContractStart=contractEndYear===null?null:new Date(contractEndYear,3,1),risk=balance===null?'N/A':burnRate===null?'GREEN':forecast<octoberStart?'RED':forecast<nextContractStart?'YELLOW':'GREEN';
      const serviceConsumption=new Map();consumption.forEach(row=>serviceConsumption.set(row.product,(serviceConsumption.get(row.product)||0)+Math.abs(row.token)));const monthlyTrend=new Map([...allMonthly.entries()].filter(([period])=>!filters.year||period.startsWith(`${filters.year}-`))),top=[...serviceConsumption.entries()].sort((a,b)=>b[1]-a[1])[0]||['N/A',0],monthly=new Map();consumption.forEach(row=>{const period=`${row.date.getFullYear()}-${String(row.date.getMonth()+1).padStart(2,'0')}`;monthly.set(period,(monthly.get(period)||0)+Math.abs(row.token));});
      return{total,balance,cur:currentPeriod,currentMonthLatestDate,prev:previousPeriod,cv:currentValue,pv:previousValue,mom:monthOverMonth,burn:burnRate,days:daysRemaining,forecast,contractEndDate,actualBalanceSeries,startingTokens:actualBalanceSeries.length?Math.max(...actualBalanceSeries.map(row=>row.balance)):null,forecastSource:burndownToCutoff.length?'Burndown snapshot + Credit Transactions after snapshot':'Credit Transactions fallback',risk,top,high:consumption.filter(row=>Math.abs(row.token)>100).length,monthly,monthlyTrend,serviceConsumption,filteredCount:sourceTx.length,periodTokenUsed,periodTokenRowCount,periodTokenNet};
    }
  };
})();
